version: 2
jobs:
  release:
    parallelism: 1
    working_directory: ~/rico
    docker:
      - image: debian
    environment:
      - VERSION_FILE: ../VERSION
      - RACKET_VERSION: 6.10.1
      - TERM: xterm
      - DEBIAN_FRONTEND: noninteractive
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y wget sqlite3 ca-certificates openssl procps bzip2
          rm -rf /var/lib/apt/lists/*
          wget https://mirror.racket-lang.org/installers/${RACKET_VERSION}/racket-${RACKET_VERSION}-x86_64-linux.sh
          echo "yes\n\n" | /bin/sh racket-${RACKET_VERSION}-x86_64-linux.sh
          raco setup
      - run: raco pkg config --set catalogs "https://download.racket-lang.org/releases/$RACKET_VERSION/catalog/" "https://pkg-build.racket-lang.org/server/built/catalog/" "https://pkgs.racket-lang.org" "https://planet-compats.racket-lang.org"
      - run: raco exe semver-from-git.rkt
      - run: tar jcvf semver-from-git.tar.bz2 semver-from-git
      - run: |
          wget https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2
          tar jxvf linux-amd64-github-release.tar.bz2
          mv bin/linux/amd64/github-release /usr/local/bin/github-release
          chmod +x /usr/local/bin/github-release
          rm -f linux-amd64-github-release.tar.bz2
      - run: ./semver-from-git $VERSION_FILE
      - run: export SEMVER=$(cat $VERSION_FILE); github-release release --user omnypay --repo rico --tag $SEMVER  --target $CIRCLE_SHA1
      - run: export SEMVER=$(cat $VERSION_FILE); github-release upload --user omnypay --repo rico --tag $SEMVER  --name semver-from-git.tar.bz2 --file semver-from-git.tar.bz2
workflows:
  version: 2
  build_test_release:
    jobs:
      - release
